### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Uleepera** [mbbsemu/mbbsemu-docker#1]
I'm a little new to manually loading a docker.  I run a 24/7 unraid server which I was hoping to run this build on.  Eric had mentioned you were looking at a docker version for the Linux port.  Any guidance you could provide to actually load this?  I googled and most seemed to indicate you could reference the github repository like any other docker repository however when I tried to run your build it won't actually pull it over.  I could be doing something wrong.  If its too soon to ask this just let me know and I'll revisit in a month or so.

**Comment by Uleepera** [comment]
I was able to attempt a build today.  Since things run slightly different on unraid I received the following error

root@Tower:/mnt/user/downloads/mbbsemu-docker# docker build -t mbbsemu .
Sending build context to Docker daemon  51.23MB
Step 1/12 : FROM mcr.microsoft.com/dotnet/core/runtime:3.1.1-buster-slim
3.1.1-buster-slim: Pulling from dotnet/core/runtime
bc51dd8edc1b: Already exists 
6848f14cfbf7: Pull complete 
01ae9269f21a: Pull complete 
e5a46ebecd63: Pull complete 
Digest: sha256:accff5e15fc3738e88ce7fa814d05fa11335863a8d63ebf86a218ef86231c517
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/runtime:3.1.1-buster-slim
 ---> abe903e47cb5
Step 2/12 : LABEL maintainer="fletcherm@gmail.com"
 ---> Running in ec93625870a5
Removing intermediate container ec93625870a5
 ---> 030d6607df8e
Step 3/12 : ENV EMULATOR_PATH /mbbsemu/
 ---> Running in 77549d65b4a3
Removing intermediate container 77549d65b4a3
 ---> 2d6aa9343fff
Step 4/12 : ENV MODULES_PATH /modules/
 ---> Running in cee242fd631d
Removing intermediate container cee242fd631d
 ---> 53002367dae3
Step 5/12 : COPY pkg/modules ${MODULES_PATH}
 ---> 63fd0cd4939a
Step 6/12 : COPY pkg/mbbsemu-linux-x64-* ${EMULATOR_PATH}
**### COPY failed: no source files were specified**
root@Tower:/mnt/user/downloads/mbbsemu-docker#

**Comment by fletcherm** [comment]
@Uleepera My bad man -- somehow I spaced on this and didn't even see this here! How embarrassing now that it's almost a year later.

I recently changed this image to be based on a LinuxServer.io base image, so it works a bit different (and better now). Can you please try again and let me know if things are any better or worse?

Thanks again for your patience.
